CREATE TABLE IF NOT EXISTS "accounts" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"expires_at" timestamp,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "address" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"address_line_1" varchar(255),
	"address_line_2" varchar(255),
	"state" varchar(255),
	"city" varchar(255),
	"zip_code" varchar(255),
	"phone_number" integer,
	"alternate_phone" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "admission_information" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admission_information_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"admission_date" varchar(255),
	"discharge_date" varchar(255),
	"admitting_physician" varchar(255),
	"reason_for_admission" text,
	"current_status" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "admitted_form" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admitted_form_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "audit_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint,
	"action" varchar(255) NOT NULL,
	"table_name" varchar(255) NOT NULL,
	"record_id" bigint,
	"old_value" text,
	"new_value" text,
	"ip_address" varchar(255),
	"user_agent" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "benefit_periods" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "benefit_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"start_date" timestamp,
	"end_date" timestamp,
	"period_number" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cardiac" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cardiac_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cardiac_assessment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cardiac_assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"cardiac_ids" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cardiovascular_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cardiovascular_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"cardiovascular_normal" varchar(255),
	"cardiovascular_abnormal" varchar(255),
	"cardiovascular_pedal_edema" varchar(255),
	"cardiovascular_jugular_distention" varchar(255),
	"cardiovascular_heart_sounds" varchar(255),
	"cardiovascular_peripheral_pulses" varchar(255),
	"cardiovascular_capillary_refill" varchar(255),
	"cardiovascular_other" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "comprehensive_pain_assessment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comprehensive_pain_assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"comprehensive_pain" integer,
	"date_of_assessment" varchar(255),
	"comprehensive_pain_included" text,
	"comments" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "discharge" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discharge_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint,
	"type_of_record" varchar(255),
	"national_provider_identifier" varchar(255),
	"certification_number" varchar(255),
	"admission_date" varchar(255),
	"reason_for_record" varchar(255),
	"discharge_date" varchar(255),
	"social_security_number" varchar(255),
	"medicare_number" varchar(255),
	"medicaid_recipient" varchar(255),
	"reason_for_discharge" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "discharge_sections" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discharge_sections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"code" varchar(1) NOT NULL,
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "discharge_sections_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dme_providers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dme_providers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"provider_name" varchar(255),
	"contact_person" varchar(255),
	"phone" varchar(255),
	"email" varchar(255),
	"address" varchar(255),
	"city" varchar(255),
	"state" varchar(255),
	"zip_code" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dnr" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dnr_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"dnr_status" varchar(255),
	"dnr_date" varchar(255),
	"dnr_notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "emergency_preparedness_level" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "emergency_preparedness_level_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"level" varchar(255),
	"description" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "endocrine" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "endocrine_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "endocrine_assessment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "endocrine_assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"endocrine_ids" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "flacc_behavioral_pain" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flacc_behavioral_pain_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"face" varchar(255),
	"legs" varchar(255),
	"activity" varchar(255),
	"cry" varchar(255),
	"consolability" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "flacc_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flacc_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"flacc_face" varchar(255),
	"flacc_legs" varchar(255),
	"flacc_activity" varchar(255),
	"flacc_cry" varchar(255),
	"flacc_consolability" varchar(255),
	"total_score" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "gastrointestinal_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gastrointestinal_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"gastrointestinal_normal" varchar(255),
	"gastrointestinal_abnormal" varchar(255),
	"gastrointestinal_appetite" varchar(255),
	"gastrointestinal_dysphagia" varchar(255),
	"gastrointestinal_nausea" varchar(255),
	"gastrointestinal_vomiting" varchar(255),
	"gastrointestinal_diarrhea" varchar(255),
	"gastrointestinal_constipation" varchar(255),
	"gastrointestinal_bowel_sounds" varchar(255),
	"gastrointestinal_bowel_movement" varchar(255),
	"gastrointestinal_abdominal_distention" varchar(255),
	"gastrointestinal_abdominal_pain" varchar(255),
	"gastrointestinal_tube_feeding" varchar(255),
	"gastrointestinal_parenteral_feeding" varchar(255),
	"gastrointestinal_other" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "genitourinary_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "genitourinary_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"genitourinary_normal" varchar(255),
	"genitourinary_abnormal" varchar(255),
	"genitourinary_urinary_pattern" varchar(255),
	"genitourinary_urinary_incontinence" varchar(255),
	"genitourinary_urinary_retention" varchar(255),
	"genitourinary_urinary_urgency" varchar(255),
	"genitourinary_urinary_frequency" varchar(255),
	"genitourinary_urinary_nocturia" varchar(255),
	"genitourinary_urinary_dysuria" varchar(255),
	"genitourinary_urinary_hematuria" varchar(255),
	"genitourinary_urinary_catheter" varchar(255),
	"genitourinary_other" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hematological" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hematological_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "integumentary" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "integumentary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "liaison_primary" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "liaison_primary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"first_name" varchar(255),
	"last_name" varchar(255),
	"phone" varchar(255),
	"email" varchar(255),
	"relationship" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "liaison_secondary" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "liaison_secondary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"first_name" varchar(255),
	"last_name" varchar(255),
	"phone" varchar(255),
	"email" varchar(255),
	"relationship" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "living_arrangements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "living_arrangements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"primary_caregiver" varchar(255),
	"primary_location_of_patient" varchar(255),
	"caregiver_availability" varchar(255),
	"patient_able" boolean,
	"need_hospice_service" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "model_has_roles" (
	"role_id" bigint NOT NULL,
	"model_type" varchar(255) NOT NULL,
	"model_id" bigint NOT NULL,
	CONSTRAINT "model_has_roles_role_id_model_type_model_id_pk" PRIMARY KEY("role_id","model_type","model_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nursing_clinical_notes" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nursing_clinical_notes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"benefit_period_id" bigint,
	"note_date" varchar(255),
	"time_in" varchar(255),
	"time_out" varchar(255),
	"patient_name" varchar(255),
	"patient_number" varchar(255),
	"location_name" varchar(255),
	"benefit_period" text,
	"dob" varchar(255),
	"location_number" varchar(255),
	"prn_visit" boolean DEFAULT false,
	"patient_identifiers" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nutrition_assessment" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nutrition_assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"nutrition_problems_type_ids" varchar(255) NOT NULL,
	"nutrition_template_ids" varchar(255) NOT NULL,
	"comments" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nutrition_problems_type" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nutrition_problems_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nutrition_template" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nutrition_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_active_problem" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_active_problem_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_active_problem_patient" varchar(255),
	"comments" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_assessments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_assessments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_level_now" integer,
	"acceptable_level_of_pain" integer,
	"worst_pain_level" integer,
	"primary_pain_site" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_assessment_in_dementia_scale" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_assessment_in_dementia_scale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"breathing" varchar(255),
	"vocalization" varchar(255),
	"facial_expression" varchar(255),
	"body_language" varchar(255),
	"consolability" varchar(255),
	"total_score" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_breakthrough" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_breakthrough_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_breakthrough_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_character" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_character_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_character_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"pain_level_now" varchar(255),
	"pain_right" varchar(255),
	"pain_left" varchar(255),
	"pain_acceptable_level" varchar(255),
	"pain_rated_by" text,
	"respiratory_rhythm" varchar(255),
	"pain_observations" text,
	"pain_duration" text,
	"pain_frequency" text,
	"pain_character" text,
	"worsened_by" text,
	"relieved_by" text,
	"effects_on_function" text,
	"current_pain_management" varchar(255),
	"breakthrough_pain" text,
	"additional_pain_information" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_duration" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_duration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_duration_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_effects_on_function" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_effects_on_function_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_effects_on_function_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_frequency" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_frequency_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_frequency_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_observations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_observations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_observations_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_rated_by" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_rated_by_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_rated_by_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_relieved_by" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_relieved_by_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_relieved_by_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_scales_tools_lab_data_reviews" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_scales_tools_lab_data_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"mid_arm_circumference" varchar(255),
	"mid_thigh_circumference" varchar(255),
	"sleep_hours" varchar(255),
	"fast" varchar(255),
	"nyha" varchar(255),
	"pps" varchar(255),
	"blood_sugar" varchar(255),
	"pt_inr" varchar(255),
	"other_reading_2" varchar(255),
	"other_reading_3" varchar(255),
	"other_reading_4" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_screening" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_screening_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"patient_screened" varchar(255),
	"date_of_first_pain" varchar(255),
	"pain_severity" varchar(255),
	"standardized_tool_pain_used" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_summary_interventions_goals" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_summary_interventions_goals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"summary_of_problem" text,
	"pain_interventions_administer_medication" varchar(255),
	"pain_interventions_administer_medication_start_date" varchar(255),
	"pain_interventions_assess_effectiveness" varchar(255),
	"pain_interventions_assess_effectiveness_start_date" varchar(255),
	"pain_interventions_assess_pain_status" varchar(255),
	"pain_interventions_assess_pain_status_start_date" varchar(255),
	"pain_interventions_non_pharmacological" varchar(255),
	"pain_interventions_non_pharmacological_start_date" varchar(255),
	"pain_goals_caregiver" varchar(255),
	"pain_goals_rating" varchar(255),
	"pain_goals_start_date" varchar(255),
	"pain_goals_end_date" varchar(255),
	"pain_caregiver_discussion_methods" varchar(255),
	"pain_achive_by_date" varchar(255),
	"pain_achive_by_date_start_date" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_vital_signs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_vital_signs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"temperature_fahrenheit" varchar(255),
	"temperature_method" varchar(255),
	"heart_rate" varchar(255),
	"heart_rhythm" varchar(255),
	"heart_rate_location" varchar(255),
	"respiratory_rate" varchar(255),
	"respiratory_rhythm" varchar(255),
	"blood_pressure_systolic" varchar(255),
	"blood_pressure_diastolic" varchar(255),
	"bp_location" varchar(255),
	"bp_position" varchar(255),
	"bp_additional_details" varchar(255),
	"pulse_oximetry" varchar(255),
	"pulse_ox_location" varchar(255),
	"pulse_ox_other_location" varchar(255),
	"bmi" varchar(255),
	"bmi_percentile" varchar(255),
	"body_height_inches" varchar(255),
	"body_weight_lbs" varchar(255),
	"body_weight_kg" varchar(255),
	"weight_source" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pain_worsened_by" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pain_worsened_by_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"pain_worsened_by_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "painad_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "painad_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"pain_assessment_behavior" varchar(255),
	"pain_assessment_negative_vocalizations" varchar(255),
	"pain_assessment_facial_expression" varchar(255),
	"pain_assessment_body_language" varchar(255),
	"pain_consolability" varchar(255),
	"painad_total_score" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "patients" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"first_name" varchar(255),
	"last_name" varchar(255),
	"middle_name" varchar(255),
	"date_of_birth" varchar(255),
	"gender" varchar(255),
	"ssn" varchar(255),
	"patient_pharmacy_id" bigint,
	"primary_diagnosis_id" bigint,
	"race_ethnicity_id" bigint,
	"dme_provider_id" bigint,
	"liaison_primary_id" bigint,
	"liaison_secondary_id" bigint,
	"dnr_id" bigint,
	"emergency_preparedness_level_id" bigint,
	"patient_identifier_id" bigint,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "patient_identifiers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_identifiers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "patient_pharmacies" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "patient_pharmacies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255),
	"address" varchar(255),
	"city" varchar(255),
	"state" varchar(255),
	"zip_code" varchar(255),
	"phone" varchar(255),
	"fax" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "payer_information" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payer_information_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"social_security" varchar(255),
	"medicare_beneficiary" varchar(255),
	"medicaid_number" varchar(255),
	"payer_info" varchar(255),
	"medicaid_recipient" boolean,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"guard_name" varchar(255) DEFAULT 'web' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "permissions_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "primary_diagnosis" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "primary_diagnosis_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"diagnosis_code" varchar(255),
	"diagnosis_description" varchar(255),
	"diagnosis_date" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "prognosis" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prognosis_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"prognosis_patient_is_imminent" boolean,
	"prognosis_patient_id" varchar(255),
	"prognosis_caregiver_id" varchar(255),
	"prognosis_imminence_id" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "prognosis_caregiver" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prognosis_caregiver_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "prognosis_imminence_of_death" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prognosis_imminence_of_death_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "prognosis_patient" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prognosis_patient_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "race_ethnicity" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "race_ethnicity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"race" varchar(255),
	"ethnicity" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "respiratory_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "respiratory_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"respiratory_normal" varchar(255),
	"respiratory_abnormal" varchar(255),
	"respiratory_effort" varchar(255),
	"respiratory_breath_sounds" varchar(255),
	"respiratory_cough" varchar(255),
	"respiratory_sputum" varchar(255),
	"respiratory_other" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"guard_name" varchar(255) DEFAULT 'web' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roles_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_has_permissions" (
	"permission_id" bigint PRIMARY KEY NOT NULL,
	"role_id" bigint PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "scale_tool_lab_data" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "scale_tool_lab_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"mac" varchar(255),
	"mtc" varchar(255),
	"sleep_time" varchar(255),
	"fast" varchar(255),
	"nyha" varchar(255),
	"other_reading_1" varchar(255),
	"blood_sugar" varchar(255),
	"pt_inr" varchar(255),
	"other_reading_2" varchar(255),
	"other_reading_3" varchar(255),
	"other_reading_4" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "sessions_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "signature" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "signature_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"signature_name" "bytea",
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "site_of_service" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "site_of_service_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "spiritual_preference" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spiritual_preference_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"patient_spiritual" varchar(255),
	"not_religious" boolean,
	"comments" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "type_of_pain_rating_scale_used" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_of_pain_rating_scale_used_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"type_of_pain_rating_scale_used_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"image" varchar(255),
	"email_verified_at" timestamp,
	"password" varchar(255),
	"remember_token" varchar(255),
	"role" varchar(255) DEFAULT 'patient',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_has_roles" (
	"user_id" bigint NOT NULL,
	"role_id" bigint NOT NULL,
	CONSTRAINT "user_has_roles_user_id_role_id_pk" PRIMARY KEY("user_id","role_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "verifications" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "visit_information" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "visit_information_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"patient_id" bigint NOT NULL,
	"visit_date" timestamp,
	"visit_time_in" varchar(255),
	"visit_time_out" varchar(255),
	"travel_time_in" varchar(255),
	"travel_time_out" varchar(255),
	"documenttation_time" varchar(255),
	"associated_mileage" varchar(255),
	"surcharge" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "vital_signs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vital_signs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"note_id" bigint NOT NULL,
	"degrees_fahrenheit" integer,
	"temperature_method" varchar(255),
	"heart_rate" integer,
	"heart_rhythm" varchar(255),
	"heart_rate_location" varchar(255),
	"other_heart_rate_location" varchar(255),
	"bp_systolic" integer,
	"bp_diastolic" integer,
	"bp_position" varchar(255),
	"bp_location" varchar(255),
	"other_bp_location" varchar(255),
	"bp_additional_readings" varchar(255),
	"respiratory_rate" integer,
	"respiratory_rhythm" varchar(255),
	"pulse_oximetry_percentage" numeric(5, 2),
	"pulse_ox_location" varchar(255),
	"pulse_ox_other_location" varchar(255),
	"body_height_inches" numeric(5, 2),
	"body_weight_ibs" numeric(5, 2),
	"body_weight_kg" numeric(5, 2),
	"body_weight_period" varchar(255),
	"bmi_kg_m2" numeric(5, 2),
	"bmi_percentage" numeric(5, 2),
	"bp_mmhg" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint accounts_user_id_users_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE cascade;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint audit_logs_user_id_users_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "cardiac_assessment" ADD CONSTRAINT "cardiac_assessment_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint cardiac_assessment_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "discharge" ADD CONSTRAINT "discharge_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint discharge_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "endocrine_assessment" ADD CONSTRAINT "endocrine_assessment_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint endocrine_assessment_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "living_arrangements" ADD CONSTRAINT "living_arrangements_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint living_arrangements_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "nutrition_assessment" ADD CONSTRAINT "nutrition_assessment_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint nutrition_assessment_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "prognosis" ADD CONSTRAINT "prognosis_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint prognosis_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint sessions_user_id_users_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "signature" ADD CONSTRAINT "signature_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint signature_patient_id_patients_id_fk already exists, skipping.';
END $do$;--> statement-breakpoint
DO $do$
BEGIN
    ALTER TABLE "spiritual_preference" ADD CONSTRAINT "spiritual_preference_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'Constraint spiritual_preference_patient_id_patients_id_fk already exists, skipping.';
END $do$;
