import { pgTable, bigint, varchar, timestamp } from 'drizzle-orm/pg-core';

export const pain_vital_signs = pgTable('pain_vital_signs', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  patient_id: bigint('patient_id', { mode: 'number' }).notNull(),
  temperature_fahrenheit: varchar('temperature_fahrenheit', { length: 255 }),
  temperature_method: varchar('temperature_method', { length: 255 }),
  heart_rate: varchar('heart_rate', { length: 255 }),
  heart_rhythm: varchar('heart_rhythm', { length: 255 }),
  heart_rate_location: varchar('heart_rate_location', { length: 255 }),
  respiratory_rate: varchar('respiratory_rate', { length: 255 }),
  respiratory_rhythm: varchar('respiratory_rhythm', { length: 255 }),
  blood_pressure_systolic: varchar('blood_pressure_systolic', { length: 255 }),
  blood_pressure_diastolic: varchar('blood_pressure_diastolic', { length: 255 }),
  bp_location: varchar('bp_location', { length: 255 }),
  bp_position: varchar('bp_position', { length: 255 }),
  bp_additional_details: varchar('bp_additional_details', { length: 255 }),
  pulse_oximetry: varchar('pulse_oximetry', { length: 255 }),
  pulse_ox_location: varchar('pulse_ox_location', { length: 255 }),
  pulse_ox_other_location: varchar('pulse_ox_other_location', { length: 255 }),
  bmi: varchar('bmi', { length: 255 }),
  bmi_percentile: varchar('bmi_percentile', { length: 255 }),
  body_height_inches: varchar('body_height_inches', { length: 255 }),
  body_weight_lbs: varchar('body_weight_lbs', { length: 255 }),
  body_weight_kg: varchar('body_weight_kg', { length: 255 }),
  weight_source: varchar('weight_source', { length: 255 }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});