import { pgTable, bigint, integer, varchar, decimal, timestamp } from 'drizzle-orm/pg-core';

export const vital_signs = pgTable('vital_signs', {
  id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
  note_id: bigint('note_id', { mode: 'number' }).notNull(),
  degrees_fahrenheit: integer('degrees_fahrenheit'),
  temperature_method: varchar('temperature_method', { length: 255 }),
  heart_rate: integer('heart_rate'),
  heart_rhythm: varchar('heart_rhythm', { length: 255 }),
  heart_rate_location: varchar('heart_rate_location', { length: 255 }),
  other_heart_rate_location: varchar('other_heart_rate_location', { length: 255 }),
  bp_systolic: integer('bp_systolic'),
  bp_diastolic: integer('bp_diastolic'),
  bp_position: varchar('bp_position', { length: 255 }),
  bp_location: varchar('bp_location', { length: 255 }),
  other_bp_location: varchar('other_bp_location', { length: 255 }),
  bp_additional_readings: varchar('bp_additional_readings', { length: 255 }),
  respiratory_rate: integer('respiratory_rate'),
  respiratory_rhythm: varchar('respiratory_rhythm', { length: 255 }),
  pulse_oximetry_percentage: decimal('pulse_oximetry_percentage', { precision: 5, scale: 2 }),
  pulse_ox_location: varchar('pulse_ox_location', { length: 255 }),
  pulse_ox_other_location: varchar('pulse_ox_other_location', { length: 255 }),
  body_height_inches: decimal('body_height_inches', { precision: 5, scale: 2 }),
  body_weight_ibs: decimal('body_weight_ibs', { precision: 5, scale: 2 }),
  body_weight_kg: decimal('body_weight_kg', { precision: 5, scale: 2 }),
  body_weight_period: varchar('body_weight_period', { length: 255 }),
  bmi_kg_m2: decimal('bmi_kg_m2', { precision: 5, scale: 2 }),
  bmi_percentage: decimal('bmi_percentage', { precision: 5, scale: 2 }),
  bp_mmhg: integer('bp_mmhg'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});